homepage: "https://aicyberchallenge.com/"
language: c
main_repo: "https://github.com/aixcc-challenges/integration-test"

fuzzing_engines:
  - libfuzzer

sanitizers:
  - address

architectures:
  - x86_64

commit_range:
  start_ref: f6eb06e419e431775d536911774f9909524c98d4~32
  end_ref: f6eb06e419e431775d536911774f9909524c98d4
