homepage: "https://github.com/apache/zookeeper"
language: jvm
primary_contact: "irali@google.com"
main_repo: "https://github.com/apache/zookeeper.git"
file_github_issue: false
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
commit_range:
  start_ref: 6942ee647377584497495d70eab0e04df34438e3~41
  end_ref: 6942ee647377584497495d70eab0e04df34438e3
