homepage: "https://sqlite.org/"
main_repo: "https://sqlite.org/src/dir"
language: c
sanitizers:
  - address
  - memory
  - undefined
architectures:
  - x86_64
fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer
commit_range:
  start_ref: 9c67c575315bc3de5b1baa2f1abeae13db3892f6~41
  end_ref: 9c67c575315bc3de5b1baa2f1abeae13db3892f6
