homepage: "https://gitlab.gnome.org/GNOME/libxml2"
language: c
primary_contact: ""
sanitizers:
  - address
architectures:
  - x86_64
fuzzing_engines:
  - libfuzzer
main_repo: 'https://gitlab.gnome.org/GNOME/libxml2.git'
commit_range:
  start_ref: 70a247ce199087796d420395716f8b83dca98368~44
  end_ref: 70a247ce199087796d420395716f8b83dca98368
