homepage: "https://curl.haxx.se/"
language: c++
primary_contact: "daniel@haxx.se"
auto_ccs:
  - "daniel.haxx@gmail.com"
  - "cmeister2@gmail.com"
  - "stefan.eissing@gmail.com"
sanitizers:
  - address
  - undefined
fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer
architectures:
  - x86_64
  - i386
main_repo: 'https://github.com/curl/curl.git'

commit_range:
  start_ref: 72edb22b8a0e1e62216b59a045147d1a863ad59b
  end_ref: HEAD
