homepage: "http://nginx.org"
main_repo: "https://github.com/nginx/nginx"
language: c
primary_contact: "xim.andrew@gmail.com"
auto_ccs:
  - pluknet@gmail.com
  - david@adalogics.com
sanitizers:
  - address

fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer

commit_range:
  start_ref: c498a935699a24720cc8857a48d0ce999e1aa6bb
  end_ref: 077e305de7e7f7a960d0ad440e7ed66f3da5a5ce
