# first model is default, other models are fallback or used for run_batch
AddDebugPrintsAgent = ["azure/gpt-4o-2024-08-06"]
CRSDiffAgent = ["azure/o4-mini-2025-04-16"]
CRSDynamicDebugAgent = ["azure/o1-2024-12-17"]
CRSPovProducerAgent = ["azure/o3-mini-2025-01-31", "azure/o4-mini-2025-04-16"]
HarnessInputEncoderAgent = ["azure/o1-2024-12-17"]
PatcherAgent = ["azure/gpt-4o-2024-08-06"]
SourceQuestionsAgent = ["azure/o1-2024-12-17"]
TriageAgent = ["azure/gpt-4o-2024-08-06"]
DedupClassifier = ["azure/gpt-4.1-2025-04-14"]
FunctionSummarizer = ["azure/gpt-4.1-2025-04-14"]
LikelyVulnClassifier = ["azure/gpt-4.1-2025-04-14"]
CRSVulnAnalyzerAgent = ["azure/o4-mini-2025-04-16"]
GenerateKaitaiAgent = ["azure/o3-mini-2025-01-31"]
HarnessInputDecoderAgent = ["azure/o1-2024-12-17"]
BranchFlipperAgent = ["azure/gpt-4.1-2025-04-14"]
LikelyFlippableClassifier = ["azure/gpt-4.1-2025-04-14"]