# first model is default, other models are fallback or used for run_batch
AddDebugPrintsAgent = ["claude-3-5-sonnet-20241022"]
CRSDiffAgent = ["o4-mini-2025-04-16"]
CRSDynamicDebugAgent = ["claude-3-5-sonnet-20241022"]
CRSPovProducerAgent = ["claude-3-7-sonnet-20250219", "claude-3-5-sonnet-20241022"]
HarnessInputEncoderAgent = ["o1-2024-12-17"]
PatcherAgent = ["claude-3-7-sonnet-20250219"]
SourceQuestionsAgent = ["o1-2024-12-17"]
TriageAgent = ["o4-mini-2025-04-16"]
DedupClassifier = ["gpt-4.1-2025-04-14"]
FunctionSummarizer = ["claude-3-5-haiku-20241022"]
LikelyVulnClassifier = ["gpt-4.1-2025-04-14"]
CRSVulnAnalyzerAgent = ["o4-mini-2025-04-16"]
GenerateKaitaiAgent = ["claude-3-5-sonnet-20241022"]
HarnessInputDecoderAgent = ["anthropic/claude-sonnet-4-20250514"]
