# first model is default, other models are fallback or used for run_batch
AddDebugPrintsAgent = ["claude-3-5-sonnet-20241022"]
CRSDiffAgent = ["claude-3-5-sonnet-20241022"]
CRSDynamicDebugAgent = ["claude-3-7-sonnet-20250219"]
CRSPovProducerAgent = ["claude-3-7-sonnet-20250219", "claude-3-5-sonnet-20241022"]
HarnessInputEncoderAgent = ["claude-3-5-sonnet-20241022"]
PatcherAgent = ["claude-3-7-sonnet-20250219"]
SourceQuestionsAgent = ["claude-3-7-sonnet-20250219"]
TriageAgent = ["claude-3-5-sonnet-20241022"]
DedupClassifier = ["azure/gpt-4.1-2025-04-14"] # classifiers only work with openai
FunctionSummarizer = ["claude-3-5-sonnet-20241022"]
LikelyVulnClassifier = ["azure/gpt-4.1-2025-04-14"] # classifiers only work with openai
CRSVulnAnalyzerAgent = ["claude-3-5-sonnet-20241022"]
GenerateKaitaiAgent = ["claude-3-5-sonnet-20241022"]
HarnessInputDecoderAgent = ["anthropic/claude-sonnet-4-20250514"]
BranchFlipperAgent = ["claude-3-7-sonnet-20250219"]
LikelyFlippableClassifier = ["azure/gpt-4.1-2025-04-14"]