AddDebugPrintsAgent = ["claude-3-5-sonnet-20241022"]
CRSDiffAgent = ["azure/o4-mini-2025-04-16"]
CRSDynamicDebugAgent = ["claude-3-5-sonnet-20241022"]
CRSPovProducerAgent = ["anthropic/claude-sonnet-4-20250514", "claude-3-5-sonnet-20241022", "o3-2025-04-16"]
HarnessInputEncoderAgent = ["o3-2025-04-16"]
PatcherAgent = ["anthropic/claude-sonnet-4-20250514"]
SourceQuestionsAgent = ["o3-2025-04-16"]
TriageAgent = ["azure/o4-mini-2025-04-16"]
DedupClassifier = ["azure/gpt-4.1-2025-04-14"]
FunctionSummarizer = ["anthropic/claude-sonnet-4-20250514"]
LikelyVulnClassifier = ["azure/gpt-4.1-2025-04-14"]
CRSVulnAnalyzerAgent = ["o4-mini-2025-04-16", "azure/o4-mini-2025-04-16"]
GenerateKaitaiAgent = ["anthropic/claude-sonnet-4-20250514"]
HarnessInputDecoderAgent = ["anthropic/claude-sonnet-4-20250514"]
BranchFlipperAgent = ["anthropic/claude-sonnet-4-20250514"]
LikelyFlippableClassifier = ["gpt-4.1-2025-04-14"]
FullModeMulti = ["anthropic/claude-opus-4-20250514"]
FullMode = ["gemini/gemini-2.5-pro", "o3-2025-04-16"]
