# first model is default, other models are fallback or used for run_batch
AddDebugPrintsAgent = ["claude-3-5-sonnet-20241022"]
CRSDiffAgent = ["azure/o4-mini-2025-04-16"]
CRSDynamicDebugAgent = ["claude-3-5-sonnet-20241022"]
CRSPovProducerAgent = ["anthropic/claude-sonnet-4-20250514", "claude-3-5-sonnet-20241022"]
HarnessInputEncoderAgent = ["azure/o3-2025-04-16"]
PatcherAgent = ["claude-3-7-sonnet-20250219"]
SourceQuestionsAgent = ["azure/o3-2025-04-16"]
TriageAgent = ["azure/o4-mini-2025-04-16"]
DedupClassifier = ["azure/gpt-4.1-2025-04-14"]
FunctionSummarizer = ["anthropic/claude-sonnet-4-20250514"]
LikelyVulnClassifier = ["azure/gpt-4.1-2025-04-14"]
CRSVulnAnalyzerAgent = ["azure/o4-mini-2025-04-16"]
GenerateKaitaiAgent = ["anthropic/claude-sonnet-4-20250514"]
HarnessInputDecoderAgent = ["anthropic/claude-sonnet-4-20250514"]
BranchFlipperAgent = ["anthropic/claude-sonnet-4-20250514"]
LikelyFlippableClassifier = ["azure/gpt-4.1-2025-04-14"]
FullMode = ["o3-2025-04-16", "gpt-4o-2024-08-06"]
FullModeMulti = ["anthropic/claude-opus-4-20250514", "gemini/gemini-2.5-pro"]
