AddDebugPrintsAgent = ["claude-3-5-haiku-20241022"]
CRSDiffAgent = ["claude-3-5-haiku-20241022"]
CRSDynamicDebugAgent = ["claude-3-5-haiku-20241022"]
CRSPovProducerAgent = ["claude-3-5-haiku-20241022"]
HarnessInputEncoderAgent = ["claude-3-5-haiku-20241022"]
PatcherAgent = ["claude-3-5-haiku-20241022"]
SourceQuestionsAgent = ["gpt-4o-mini-2024-07-18"]
TriageAgent = ["claude-3-5-haiku-20241022"]
DedupClassifier = ["azure/gpt-4.1-nano-2025-04-14"]
FunctionSummarizer = ["azure/gpt-4.1-nano-2025-04-14"]
LikelyVulnClassifier = ["azure/gpt-4.1-nano-2025-04-14"]
CRSVulnAnalyzerAgent = ["claude-3-5-haiku-20241022"]
GenerateKaitaiAgent = ["azure/gpt-4.1-nano-2025-04-14"]
HarnessInputDecoderAgent = ["azure/gpt-4o-mini-2024-07-18"]
FullMode = ["azure/gpt-4.1-nano-2025-04-14"]
LikelyFlippableClassifier = ["azure/gpt-4.1-nano-2025-04-14"]
