AddDebugPrintsAgent = ["claude-3-5-haiku-20241022"]
CRSDiffAgent = ["claude-3-5-haiku-20241022"]
CRSDynamicDebugAgent = ["claude-3-5-haiku-20241022"]
CRSPovProducerAgent = ["claude-3-5-haiku-20241022"]
HarnessInputEncoderAgent = ["anthropic/claude-sonnet-4-20250514"]
PatcherAgent = ["claude-3-5-haiku-20241022"]
SourceQuestionsAgent = ["gpt-4o-mini-2024-07-18"]
TriageAgent = ["claude-3-5-haiku-20241022"]
DedupClassifier = ["gpt-4.1-mini-2025-04-14"]
FunctionSummarizer = ["gpt-4o-mini-2024-07-18"]
LikelyVulnClassifier = ["gpt-4.1-mini-2025-04-14"]
CRSVulnAnalyzerAgent = ["claude-3-5-haiku-20241022"]
GenerateKaitaiAgent = ["gpt-4o-mini-2024-07-18"]
HarnessInputDecoderAgent = ["gpt-4o-mini-2024-07-18"]
FullMode = ["gpt-4o-mini-2024-07-18"]
FullModeMulti = ["gpt-4o-mini-2024-07-18"]
LikelyFlippableClassifier = ["gpt-4.1-mini-2025-04-14"]