homepage: "https://www.freerdp.com/"
main_repo: "https://github.com/FreeRDP/FreeRDP"
language: c
primary_contact: ""
builds_per_day: 4
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
architectures:
  - x86_64
commit_range:
  start_ref: 6dfccd177f6f94886348123c9931acae473b8bce~41
  end_ref: 6dfccd177f6f94886348123c9931acae473b8bce